keys:
  - &peter age1d085lpynkxxf0mfus0rd3qq0r38clwz9d5ddrl79x982z00j6qsqq8f54g
  - &system_tc1 age1en39r6ynnsslwdjkrevs48z886ach4rnjea3u3uu734l8r2waa7s5qjm2d
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *peter
      - *system_tc1
