environment: ENC[AES256_GCM,data:jkeI0XqU4BBkkWnvm5dpcn6H9WWUWMEx6/ORt2JYshg6r5LhO4obLWMD7T/w03sVz50pOF0vgkP3tYwmMdT5AbKosalSoULbH6RufcRvRQsETqZrZhmROZ98yq9EwwEtfYi91ztL7Nci8Y+18StiBB5KljM=,iv:DhDJxFl7DRyRflw3X6jGSXfZ1NDy7u+G2wtykGoWit8=,tag:87h44BEJ8fgmU4JAOViiPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d085lpynkxxf0mfus0rd3qq0r38clwz9d5ddrl79x982z00j6qsqq8f54g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRXQ3NHZ4dDhpMWtSMEsx
            c2FsTmwwRmVpK0Vyd1dSZ1dPbG8zWVU3YkF3CnZCa2ZjYjlnQU5VdnRIQUFqS2pj
            SE1CV1RRWG9tVDFHY1dua2hpdWsya1EKLS0tIEJlb0JQYTVaS0QvTDlVMHdncytm
            Ynhrc1NZRnY4OU1GWmNIektNRUtHR3MKlGLdfRFlfqjK9YxG1K0qS8ThAtCurGkN
            pEYSkauG/F1+UNCkFZgOYgRap6LHMS0IZAuTm8XBll8RPUIM9+TjVA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ps0v726nguddv4rxvf3ja4hz0jdtgdlru4dckhazqhm2k5hmspzs9sudjk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTelVyUnEwQWkrQjhXdmlZ
            L2xaYkRleEdYeEhhb0R0Q0RNNjlGYVdlU0c4CnBjRFJCb3pUVXhFNFFtVjVON3d1
            M1p2TllSaWI0UWxwa2pnT2pjMy95U1UKLS0tIE1BWDB2VXZ4K0tDa3RmSUg3RFFF
            UFBIazR0ZythR2JTOEg5eVRXdEk1bmMKLc1zLX5chKA8t+6yOAex36I/eW7Mz8bx
            TnuHvHWybGtQbYU4MqWPY/BkWRCIzvDE8HILbbCGWt0hRu7mXIkvzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-14T09:04:23Z"
    mac: ENC[AES256_GCM,data:ihfV18t6BA4+Bpz14XHBfY0jmmmRDEsxbsvumqQqQZ9GtnPRNe5qPim8mvctUm4fXfqsVPVc6Z4oPhqnEv/jpyuotDwJEcpTMgzXowue3l0j6+QG/IP9t/i+150Ej2SzggeWLIjRXkP6B4MeN0LYwNjXMbRCiaIZ5Us4G9zJG9o=,iv:Q5NCXs6JuXP/jeJZJK+PO903aHAqulkUEcHbLI5SmtQ=,tag:7lWp1HrRoZ4L4T3TENWPVg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
