environment:
    apitoken: ENC[AES256_GCM,data:U1yXSu9zIXuz6wwM8KvHJcs9dvB8xUMyrahJtTNlrVI=,iv:DJh/Ok5c4SHU24txejApYhv4Xdr6f2q4SJbmSq+vhgU=,tag:mqPzk9vHOmqyuvUYeGab3A==,type:str]
    zoneid: ENC[AES256_GCM,data:lPNZ5/c1PJGLlq092P1lF9vAXeDVAA==,iv:08VNGsuDzFRahcgSU9KUI9iZ3QOn3TW39fMTEFkbOQQ=,tag:01Db/+6kr1vDlP+03KwnIA==,type:str]
    recordid: ENC[AES256_GCM,data:oThkiq2K24pFlOSQ0I4A7C42mEtlUsh3ld2OIo8WnJA=,iv:x1OBP62bST0dhQe9VuYcuPOvBFEiuIW3W2m2TvkUmSk=,tag:riyAR+ia3CY8WrvC0BBaWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d085lpynkxxf0mfus0rd3qq0r38clwz9d5ddrl79x982z00j6qsqq8f54g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTS9wbXNmUUFEOHRuNENs
            SU0yQ3l5azd5U2szOTJ5Z2lsNHlleGtBemw0CmtoL0FNMU5QVURWeUZPQk85Z20w
            bHFSWldMN0NSMFFzY2M4ZUxCUlBESGcKLS0tIC9HY05OdnF0SzFmSXFKUHlzK3pn
            eUVXNWlqNHB2YzA2UnhyQ3pNbmU4Q2sKcfD4LLovSjCr0LTh6rfVHCuAvP9dczHP
            Bxa1HGxN+sECs9/YPSHeOkEmlgoiPYBlXH93svTCvftTYhMMJIayfQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1en39r6ynnsslwdjkrevs48z886ach4rnjea3u3uu734l8r2waa7s5qjm2d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZFd3ZkVicE5WM3BSclBN
            czZxdDZid2UvS3BJTDdWU0M0TjYvcDErS2o0CkwrZVB4SXNGV0pNMWVaK2owZFdJ
            dnJONFgxUEpIODY0Mkdac01lQlhmc2cKLS0tIEFjS3NSYzJtNDA3anBWbXZPbG93
            eUQ1V2hWZWI2bEdqa3Z3RVJYSk9oK0EKJdfzjo646MsqZbrW7M/RVLXp0aKv8BRc
            lWWYoCLAz3zVa+BP/wG25jBRthS4SNi+U6BZi9ezrOAxFz/L89zKPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-14T09:11:49Z"
    mac: ENC[AES256_GCM,data:2NJB2p6UaRZ3aBEdmROVPtY1ps1GNkEAjdogLHKoWLo83XJ5nzHAMuvUoSRk88CKUbr3XGwYEGhzG5XBTeDKxpdUXnj4Xc39H5Gy4n+3725yN2Z6+KAbcxiLaNDmhk3Mi4Jty2iU/YPkkjWlTwhnX7UbvztRbjHEIQ9YOqHxh6Q=,iv:KYz5w7TCBScJgScXbBFGmn1P09ZCX1OI9J7DBYGKMqM=,tag:Zo0HguR7Bap3z6ZSAmWbyw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
