environment: ENC[AES256_GCM,data:aoV7AMVhauKUXu7yVhDnGEoT4Ye+BiHm0hXPuXUyOZ1Qzs4vQPVtQ1/nWYbOGyP7uJiv6gnAO8IV+P95SHWqTt+qnXV7e0t2zr41AIyWPpfIvCuYx2RZ4D8HCwnmeEcLYV+WgzDOW9VfJnxns/Era5Y=,iv:ljyQKWRn1cBW01kfYIlzrLeSb0gKURIPFRydMa8LSoQ=,tag:0zpN+nKlWZ9FKlwHQ3NB5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d085lpynkxxf0mfus0rd3qq0r38clwz9d5ddrl79x982z00j6qsqq8f54g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRXQ3NHZ4dDhpMWtSMEsx
            c2FsTmwwRmVpK0Vyd1dSZ1dPbG8zWVU3YkF3CnZCa2ZjYjlnQU5VdnRIQUFqS2pj
            SE1CV1RRWG9tVDFHY1dua2hpdWsya1EKLS0tIEJlb0JQYTVaS0QvTDlVMHdncytm
            Ynhrc1NZRnY4OU1GWmNIektNRUtHR3MKlGLdfRFlfqjK9YxG1K0qS8ThAtCurGkN
            pEYSkauG/F1+UNCkFZgOYgRap6LHMS0IZAuTm8XBll8RPUIM9+TjVA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ps0v726nguddv4rxvf3ja4hz0jdtgdlru4dckhazqhm2k5hmspzs9sudjk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTelVyUnEwQWkrQjhXdmlZ
            L2xaYkRleEdYeEhhb0R0Q0RNNjlGYVdlU0c4CnBjRFJCb3pUVXhFNFFtVjVON3d1
            M1p2TllSaWI0UWxwa2pnT2pjMy95U1UKLS0tIE1BWDB2VXZ4K0tDa3RmSUg3RFFF
            UFBIazR0ZythR2JTOEg5eVRXdEk1bmMKLc1zLX5chKA8t+6yOAex36I/eW7Mz8bx
            TnuHvHWybGtQbYU4MqWPY/BkWRCIzvDE8HILbbCGWt0hRu7mXIkvzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-14T08:44:43Z"
    mac: ENC[AES256_GCM,data:M2EEn6u8GacLIkFVomgPv47mY76u3w2UblKwiX3VFXa3DMHz7QMV8AXOVOajXQR11EOfzNbfyzSRsjLbXmQXp2QLHP56eaBcyItMNhR6Yqw0WoA7wNIM/EibWxpoDqAoHjHL2IxdMq9DR81ouvgodOWoMY3YVXe6u+Uir+8JJsE=,iv:9/YLfdmT/rJI+N3hhABCSY9YvPrEsvlebVKnOhV3EiM=,tag:fQt6Xtqy1WWTHf32qKHXYA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
